lexik_jwt_authentication:
    secret_key: '%env(resolve:JWT_SECRET_KEY)%'
    public_key: '%env(resolve:JWT_PUBLIC_KEY)%'
    pass_phrase: '%env(JWT_PASSPHRASE)%'
    # Time To Live : durée de vie du token
    ## pendant le developpement, plusieur solution
    ## 1. vous n'avez pas envie de regénérer des tokens tout les jours = token_ttl:2678400
    ## 2. dans la vrai vie, en dev, 18h : 64800
    token_ttl: 64800 # in seconds, default is 3600
