GET http://localhost:8000/api/genres
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Nzg3ODEzMjYsImV4cCI6MTY3ODg0NjEyNiwicm9sZXMiOlsiUk9MRV9BRE1JTiJdLCJ1c2VybmFtZSI6ImFkbWluQGFkbWluLmNvbSJ9.uQPOKIxoi9Eu58RC82tpsaeCZyooEsUHgyugZmkiHiSKM5A5-vJjkVpCL29OmcHWZcQ4QORcrsE5WtGVhPNd3JH7ORvnf6aF4W5zgpEul4K9elwB1L_KRU1ZMP2u7r-dYlmsloIdF9H3M4U7muoVA4hAILCLaZP5e0n2pIfKMMiJGF4lhCjUbPSusRGp_kAC07WCURwqzMwfefSXLNSUg7YSv-bp8xJ4CnoC4bYedFvQYxPRF8ZM0T1Tl0_jyKQPJJlCK2Ji_3d3Uv_edOwoabOfTXvwteZy10c00Q_tg0xiN6zTPddfWiAC_vnRaAsReRxuhOzmKaaRi1fQCWzjEw
